### ISSUE TITLE
opt_out fails with TypeError

### ISSUE THREAD

**Issue by CharlieLaughton** [popylar/popylar#24]
Nice simple package, just what I need, but:
Calling popylar.opt_out() leads to an error:

```
>>> import popylar
>>> r = popylar.track_event('UA-86484662-2', 'test', 'test_track_event')
>>> print r.status_code
200
>>> popylar.opt_out()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pazcal/Library/Python/2.7/lib/python/site-packages/popylar/popylar.py", line 29, in opt_out
    parser['user']['track'] = False
  File "/Users/pazcal/Library/Python/2.7/lib/python/site-packages/backports/configparser/__init__.py", line 1283, in __setitem__
    _, key, value = self._parser._validate_value_types(option=key, value=value)
  File "/Users/pazcal/Library/Python/2.7/lib/python/site-packages/backports/configparser/__init__.py", line 1221, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
>>> 
```
I can fix this by changing line 29 in popylar.py from:
```
   parser['user']['track'] = False
```
to:
```
   parser['user']['track'] = "False"
```
I don't mind cloning and doing this via a pull request but seems so minor a fix it's not really worth it.
Charlie

**Comment by arokem** [comment]
Thanks for reporting! I am happy to hear that someone has found this useful. 
I have your suggestion implemented, with some tests, in #25 (it's still failing for some reason that eludes me, but unrelated to this change).
